### ISSUE TITLE
invisible

### ISSUE THREAD

**Issue by tonibanks** [ESX-Org/instance#12]
Invisible all player, once the other player enter instance.

**Comment by bastienbichonparadize** [comment]
Experiment this issue to. Rollback to previous version.

**Comment by KingRyuShin** [comment]
having the same issue.. when someone enter a instance, everybody on the server become invisible

**Comment by aultra** [comment]
On our server, this issue occurs when an instanced player logs out.

**Comment by ArmoredSoldiers** [comment]
same problem

**Comment by XvenDeR** [comment]
send your server.cfg resources ill look in to it, some bad resources causes this

**Comment by noobiiz** [comment]
Same here

**Comment by Oreax** [comment]
I updated to this version of **instance** in an attempt to solve involuntary instancing. We've tried it only one time that we _all_ became invisible and pretty much had to restart the server. We don't get instanced anymore it would seem though. (updated essentialmode too though)

I suppose, without knowing that this bit is false putting people in playersToHide? - Looking up this native **SetEntityVisible(otherPlayerPed, false, false)**, it says it should be 0 at the end, and not false. I don't know if that does anything either. Just shooting my thoughts out there, hoping we can have it resolved :)
`Citizen.CreateThread(function()
	while true do
		Citizen.Wait(10)
		local playerPed = PlayerPedId()

		-- Hide all these players
		for player,_ in pairs(playersToHide) do
			local otherPlayerPed = GetPlayerPed(player)
			SetEntityVisible(otherPlayerPed, false, false)
			SetEntityNoCollisionEntity(playerPed, otherPlayerPed, false)
		end
	end
end)`

**Comment by ModatherM** [comment]
Well, we have the same problem and we don't know how we can fix it

**Comment by ModatherM** [comment]
@Oreax Didn't work...
if you could please share your fixed Instance + esx_proberty i would be so thankful

**Comment by ElPumpo** [comment]
Duplication of #10
