### ISSUE TITLE
64 onesync optimiced?

### ISSUE THREAD

**Issue by MVPLegion** [ESX-Org/instance#6]
i have 64 slots onesync sv and when some are using instance this resource drop -ms and fps error warning
![d98566084def58ee5d65a4e1233bff04](https://user-images.githubusercontent.com/50975839/58471559-714ad680-8144-11e9-929e-c47fcc46242f.png)
.

**Comment by bozoweed** [comment]
hi you player get visible only in same instance or it's buged and everyone still visible ?
because in my onesync server everyone stay visible ... 

for you request 
go to  ligne 206
-- Instance players
Citizen.CreateThread(function()
	while true do

		Citizen.Wait(0)-- change this to 1 or more ushe can help you to get better fps

**Comment by ItsikNox** [comment]
Have you tried to change the config.maxplayer from 32 to 255?

In config.lua

**Comment by ItsikNox** [comment]
> hi you player get visible only in same instance or it's buged and everyone still visible ?
> because in my onesync server everyone stay visible ...
> 
> for you request
> go to ligne 206
> -- Instance players
> Citizen.CreateThread(function()
> while true do
> 
> ```
> 	Citizen.Wait(0)-- change this to 1 or more ushe can help you to get better fps
> ```

Have you tried to change the config.maxplayer from 32 to 255?

In config.lua

**Comment by bozoweed** [comment]
sure

**Comment by MVPLegion** [comment]
> > hi you player get visible only in same instance or it's buged and everyone still visible ?
> > because in my onesync server everyone stay visible ...
> > for you request
> > go to ligne 206
> > -- Instance players
> > Citizen.CreateThread(function()
> > while true do
> > ```
> > 	Citizen.Wait(0)-- change this to 1 or more ushe can help you to get better fps
> > ```
> 
> Have you tried to change the config.maxplayer from 32 to 255?
> 
> In config.lua

Hi, yes i have it = 255 :S

**Comment by RikoDEV** [comment]
https://github.com/ESX-Org/instance/pull/8

**Comment by ElPumpo** [comment]
https://github.com/ESX-Org/instance/issues/7
